version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  search:
    image: elasticsearch
    ports:
      - "9200:9200"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
